name: video_sync
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cffi=1.15.1
  - cryptography=38.0.1
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight-compute=12.0.0
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.0.76
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.0.90
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.0.90
  - cuda-runtime=11.6.1
  - cuda-sanitizer-api=12.0.90
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - flit-core=3.6.0
  - freetype=2.12.1
  - future=0.18.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lerc=3.0
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcurand=10.3.1.50
  - libcurand-dev=10.3.1.50
  - libcusolver=11.3.4.124
  - libcusolver-dev=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.8
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libpng=1.6.37
  - libtiff=4.4.0
  - libuv=1.40.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nsight-compute=2022.4.0.15
  - numpy-base=1.21.5
  - openssl=1.1.1s
  - pip=22.2.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - python=3.7.13
  - pytorch=1.13.0
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - requests=2.28.1
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.39.3
  - tk=8.6.12
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - wheel=0.37.1
  - xz=5.2.8
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - beautifulsoup4==4.11.1
    - charset-normalizer==2.1.1
    - colorama==0.4.6
    - cycler==0.11.0
    - decorator==4.4.2
    - einops==0.6.0
    - filelock==3.8.2
    - fonttools==4.38.0
    - freetype-py==2.3.0
    - gdown==4.6.0
    - glfw==2.5.5
    - h5py==3.7.0
    - hsluv==5.0.3
    - imageio==2.22.3
    - imageio-ffmpeg==0.4.7
    - importlib-metadata==5.1.0
    - kornia==0.6.8
    - kornia-moons==0.2.3
    - matplotlib==3.5.3
    - moviepy==1.0.3
    - numexpr==2.8.4
    - numpy==1.21.6
    - opencv-contrib-python==4.6.0.66
    - opencv-python==4.6.0.66
    - packaging==21.3
    - pandas==1.3.5
    - pillow==9.3.0
    - proglog==0.1.10
    - pydegensac==0.1.2
    - pyparsing==3.0.9
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pyyaml==6.0
    - scipy==1.7.3
    - soupsieve==2.3.2.post1
    - tables==3.7.0
    - tcod==13.8.1
    - torch==1.13.0
    - torchvision==0.14.0
    - tqdm==4.64.1
    - transforms3d==0.4.1
    - urllib3==1.26.12
    - vispy==0.12.1
    - yacs==0.1.8
    - zipp==3.11.0
